version: "3.9"

# Stack para los ejemplos de Kafka + RabbitMQ.
# Levanta con:    docker compose -f docker-compose.messaging.yml up -d
# Apaga con:      docker compose -f docker-compose.messaging.yml down -v

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: hw-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: hw-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: hw-rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Mgmt UI -> http://localhost:15672  (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
