quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER:aquavitae_app}
quarkus.datasource.password=${DB_PASSWORD:2IrgNq.~{eDS|CM8}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:mysql://35.232.206.95:3306/AquaVitaeDB}

  firebase.credentials=${FIREBASE_CREDENTIALS:src/main/resources/aquavitae-76bfa-firebase-adminsdk-fbsvc-56778c9f37.json}


  OpenMeteoClient".url=https://api.open-meteo.com/v1/forecast?latitude=21.88,30.5,26,19,27.3,19.1,16.5,28.6,19.43,24.9,2
  1,17.6,20.5,20.6,19.3,19.2,18.7,21.8,25.5,17.1,18.8,20.8,19.6,22.6,25,29.7,18,24.3,19.3,19.3,20.7,23.3&longitude=-102.
  29,-115.1,-111.7,-90.5,-101.7,-103.7,-92.5,-106.1,-99.13,-104.9,-101.2,-100,-98.8,-103.5,-99.6,-101.8,-99.1,-104.8,-99
  .8,-96.5,-97.9,-99.8,-88.1,-100.4,-107.5,-110.8,-92.6,-98.6,-98.2,-96.5,-88.9,-102.7&daily=temperature_2m_min,rain_sum
  ,showers_sum,temperature_2m_max&hourly=temperature_2m,relative_humidity_2m,rain,evapotranspiration,temperature_80m,tem
  perature_120m,temperature_180m,soil_temperature_0cm,soil_temperature_6cm,soil_temperature_18cm,soil_temperature_54cm,s
  oil_moisture_0_to_1cm,soil_moisture_1_to_3cm,soil_moisture_3_to_9cm,soil_moisture_9_to_27cm,soil_moisture_27_to_81cm&c
  urrent=temperature_2m,rain,showers&past_days=0&forecast_days=7
  quarkus.rest-client."org.acme.infrastructure.client.NasaPowerClient".url=https://power.larc.nasa.gov

  # fuente clima activa
  fuente.clima.activa=openMeteo

  # Hibernate
  quarkus.hibernate-orm.database.generation=update
  quarkus.hibernate-orm.log.sql=true
  quarkus.hibernate-orm.log.format-sql=true
  
  # REST client para las APIs
  # Open?Meteo
  open-meteo-api/mp-rest/url=https://api.open-meteo.com
  open-meteo-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
  
  # NASA POWER
  nasa-power-api/mp-rest/url=https://power.larc.nasa.gov
  nasa-power-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

  # SMN (CONAGUA)
  smn-api/mp-rest/url=https://smn.conagua.gob.mx
  smn-api/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

  # scheduler
  quarkus.scheduler.enabled=true

# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173,https://aquavitae-app.web.app,https://aquavitae-app.firebaseapp.com
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=content-type,authorization
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=24H
